language: python
python:
  - "3.6"
cache: pip
install: 
  - pip install google_streetview
script:
  - google_streetview -s key="AIzaSyDLzW6n52tcRTGboOOepiKelNVdLC9qSzA"
  - python -m unittest
  - google_streetview -d
