language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install: 
  - pip install git+https://github.com/rrwen/google_streetview
  - pip install coveralls
script:
  - google_streetview -s key="AIzaSyDLzW6n52tcRTGboOOepiKelNVdLC9qSzA"
  - coverage run --source=google_streetview -m unittest
  - google_streetview -d
